### PR TITLE
✨ Add WaitForUndoEffect and fix labels when swiping

### LINKED ISSUE #99: Swipes over TEs have wrong labels.
## Description
When swiping from left to right on a TE, the green overlay appears and the TE gets continued. The label on the green overlay says 'Delete' though. Same story for swiping right.
Screenshot 2020-03-27 at 15 27 39

## Definition of done
Label when swiping left says 'Continue', when swiping right 'Delete'.

### LINKED ISSUE #102: Introduce the WaitForUndoEffect
## Description
We need to add the effect that will actually delete time entries that are pending because of the undo.

## Dependencies
This PR needs the `CommitDeletion` action, introduced on #101 

## Definition of done
- [ ] The effect that asynchronously waits for [5 seconds](https://github.com/toggl/mobileapp/blob/develop/Toggl.Core/Helper/Constants.cs#L26) and then emit a `CommitDeletion` action is added
- [ ] Make actions that delete (swipes) emit the following:
  - [ ] If there are no entries in the `entriesPendingDeletion` property, simply emit the `WaitForUndo` effect rather than emitting delete effects immediatelly
  - [ ] If there are entries in the  `entriesPendingDeletion` property, emit effects to delete each of those entries and also the `WaitForUndo` effect.
- [ ] Tests that cover all this new behavior are added

### PR DESCRIPTION
**Pull request by pdrj**
### Summary
This adds and uses WaitForUndoEffect. This also fixes labels when swiping TEs.

### Technical considerations
The effect is pretty straightforward. In tests, rather than having them wait for 5s, we could use a context to advance time (I think Daivid introduced it in one of his recent PRs).

### Why is it done like this and not some other way?
I'm open to any suggestions!

### Relationships

Closes #102 
Closes #99 

---
### Pull Request checklist

- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

### CODE REVIEW

File: timer/src/main/java/com/toggl/timer/log/domain/TimeEntriesLogReducer.kt [hunk 1]
```diff
@@ -55,7 +54,16 @@ class TimeEntriesLogReducer @Inject constructor(private val repository: TimeEntr
...
+                        SwipeDirection.Left -> {
+                            val entriesToCommitDeletion = state.value.entriesPendingDeletion
+                            val entriesToDelete = listOf(swipedEntry.id)
+                            state.value = state.value.copy(entriesPendingDeletion = entriesToDelete.toSet())
+
+                            val deleteEffects = prepareDeleteEffects(state, entriesToCommitDeletion)
+
+                            deleteEffects.add(WaitForUndoEffect(entriesToDelete))
+                            deleteEffects
+                        }
```
Comment (heytherewill) [inline timer/src/main/java/com/toggl/timer/log/domain/TimeEntriesLogReducer.kt:66]: Couldn't all that be extracted into a method to prevent duplication of code?

File: timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt [hunk 2]
```diff
@@ -0,0 +1,16 @@
+package com.toggl.timer.log.domain
+
+import com.toggl.architecture.core.Effect
+import kotlinx.coroutines.delay
+
+class WaitForUndoEffect(
+    private val timeEntryIdsToDelete: List<Long>
+) : Effect<TimeEntriesLogAction> {
+    private val timeEntryDeletionDelayMs = 5000L
```
Comment (heytherewill) [inline timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt:9]: This needs to be moved to `:common` because it needs to be reused by the UI

File: timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt [hunk 3]
```diff
@@ -123,14 +123,14 @@ class TimeEntriesLogFragment : Fragment(R.layout.fragment_time_entries_log) {
...
-            text = getString(R.string.continue_this),
+            text = getString(R.string.delete),
             backgroundColor = leftSwipeColor,
             textColor = actionTextColor,
             fontSize = actionFontSize,
             textPadding = actionPadding
         )
         val swipeRightParams = SwipeActionParams(
-            text = getString(R.string.delete),
+            text = getString(R.string.continue_this),
```
Comment (heytherewill) [inline timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt:133]: why `continue_this`? 🤔

File: timer/src/test/java/com/toggl/timer/log/domain/WaitForUndoEffectTests.kt [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+import kotlin.system.measureTimeMillis
+
+class WaitForUndoEffectTests : FreeSpec({
+
+    "The WaitForUndoEffect" - {
+        "when executed, waits and then emits CommitDeletion" - {
+            val effect = WaitForUndoEffect(listOf(1, 8, 1337))
+
+            var action: TimeEntriesLogAction? = null
+            val elapsed = measureTimeMillis {
```
Comment (heytherewill) [inline timer/src/test/java/com/toggl/timer/log/domain/WaitForUndoEffectTests.kt:15]: Can't you mock the time using a test scope so we don't actually need to wait for 5 seconds?

File: timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt (hunk 3 above)
Comment (pdrj) [reply timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt:133]: I just swapped what was already in there, haven't added any resources ;)

File: timer/src/main/java/com/toggl/timer/log/domain/TimeEntriesLogReducer.kt (hunk 1 above)
Comment (pdrj) [reply timer/src/main/java/com/toggl/timer/log/domain/TimeEntriesLogReducer.kt:66]: It could 👍

File: timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt (hunk 2 above)
Comment (pdrj) [reply timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt:9]: How so? Deletions from the edit view will have a 'popup' confirmation. Did you have something else in mind?

File: timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt (hunk 3 above)
Comment (heytherewill) [reply timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt:133]: Let's maybe rename this resource?

File: timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt (hunk 2 above)
Comment (heytherewill) [reply timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt:9]: This == the 5000L constant. It will be reused by the UI to display the undo toast

Comment (pdrj) [reply timer/src/main/java/com/toggl/timer/log/domain/WaitForUndoEffect.kt:9]: Haha 😂 demonstratives strike again

File: timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt (hunk 3 above)
Comment (pdrj) [reply timer/src/main/java/com/toggl/timer/log/ui/TimeEntriesLogFragment.kt:133]: Sure
