### PR TITLE
Make database time entries syncable and extend sync properties

### LINKED ISSUE #671: Make DatabaseTimeEntry properties syncable
## Description
Refactor all DatabaseTimeEntry properties to `*SyncProperty` types with the exception of `Id` and `serverId`

## Dependencies
#672  

## Definition of done
- [ ] Refactor all properties to corresponding `*SyncProperty` variants.
- [ ] Update all converter extension methods and make sure our domain models stay the same and are using "current" variant of `SyncProperty`

### PR DESCRIPTION
**Pull request by semanticer**
### Summary
This makes our DatabaseTimeEntries ready for the syncing age. 

### Technical considerations
Since the DatabaseTimeEntry is now superset of regular domain TimeEntry we need to change repository a little bit where we need to first query current DatabaseTimeEntry and update it with the new TimeEntry domain model rather than simply transforming TimeEntry to DatabaseTimeEntry as we did before.

I'm not yet sure how to handle relation to tags. Maybe I should do this in #711 ?

### Why is it done like this and not some other way?
Unfortunately, I couldn't find a way how to make some abstraction over `*SyncProperties` so there is some repetitive code. Room and the fact that data classes with their `copy` method are not implementing any common interface is making this abstraction very hard to do, but let me know if you have any suggestions.  

### Relationships

Closes #671 

### Pull Request checklist

- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

### Pointers
I've made some effort to separate commits logically so you can take advantage of that.  

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Anyone

### CODE REVIEW

File: repository/src/main/java/com/toggl/repository/Repository.kt [hunk 1]
```diff
@@ -154,12 +156,20 @@ class Repository(
     }
 
     override suspend fun editTimeEntry(timeEntry: TimeEntry): TimeEntry {
-        return timeEntryDao.updateTimeEntryWithTags(timeEntry.toDatabaseModel()).run { timeEntry }
+        val oldDatabaseTimeEntry = timeEntryDao.getOneTimeEntryWithTags(timeEntry.id)
+        val newDatabaseTimeEntry = oldDatabaseTimeEntry updateWith timeEntry
```
Comment (heytherewill) [inline repository/src/main/java/com/toggl/repository/Repository.kt:160]: That's :sogood:
