### PR TITLE
Make it crash

### LINKED ISSUE #108: Force app to crash when an error is thrown
## Description
At the moment our app is silently swallowing the exception and then misbehaving. We don't want that. I suspect this is because of the call to [`GlobalScope.launch`](https://github.com/toggl/android/blob/master/architecture/src/main/java/com/toggl/architecture/core/Store.kt#L65) in our store. 

## Definition of done
- [ ] When an exception is thrown in a reducer, the app crashes

### PR DESCRIPTION
**Pull request by daividssilverio**
### Summary
This PR basically makes our `TogglApplication` be the provider of the coroutine scope used by our centralized `Store`, instead of using the `GlobalScope`.

### Technical considerations
Note that the store is processing the app actions in the main thread.
I've tried making it work on the `IO/Default` threads out of curiosity but they just wouldn't crash for some reason (still trying to figure out why...).

### Why is it done like this and not some other way?
Using the `GlobalScope` is not recommended as we don't have control over the jobs being created by it and we are not handling their exceptions directly.
By creating our own scope we have more control of when/where our coroutines are running (at least the ones created off the store scope). Please note that whenever we use `lifecycleScope`, `viewModelScope`, they will use those scopes.

### Relationships
Closes #108 

---
### Pull Request checklist
- [ ] The code does not hinder the app's performance
- [ ] The code does not introduce regressions
- [ ] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests

### Pointers
At least run the app, take a look at the logging reducer, compare with it how it was before to make sure you are not surprised by anything.

One thing that I've noticed is that effects now are running sequentially, check the loading effects for example, compare it with how it was before the changes in this PR.

Try crashing the app from different reducers or parts of the app you think weren't crashing before.

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

## Merge permissions
🦑 it after at least 2 @toggl/androids have reviewed.

### CODE REVIEW

**Comment by heytherewill** [comment]
> Note that the store is processing the app actions in the main thread
This is fine. Any IO/CPU bound work needs to marshall, and using the main thread for dispatching ensures order :)

File: app/src/main/java/com/toggl/TogglApplication.kt [hunk 1]
```diff
@@ -1,24 +1,43 @@
...
     @Inject
     lateinit var appInitializers: AppInitializers
 
+    @Inject
+    lateinit var dispatchersProviders: DispatcherProvider
+
+    lateinit var applicationJob: Job
+
+    override val coroutineContext: CoroutineContext
+        get() = dispatchersProviders.main + applicationJob
```
[the remark this answers is not in the document]
Comment (daividssilverio) [reply app/src/main/java/com/toggl/TogglApplication.kt:33]: Indeed, I don't see a reason why not.

File: app/src/main/java/com/toggl/TogglApplication.kt [hunk 2]
```diff
@@ -28,4 +48,12 @@ class TogglApplication : Application(), OnboardingComponentProvider, TimerCompon
 
     override fun provideTimerComponent(): TimerComponent =
         appComponent.timerComponent().create()
+
+    override fun getStoreScope(): CoroutineScope =
+        this
+
+    override fun onTerminate() {
```
Comment (semanticer) [inline app/src/main/java/com/toggl/TogglApplication.kt:55]: From the `onTerminate` docs:
```
This method is for use in emulated process environments.  It will never be called on a production Android device, where processes are removed by simply killing them; no user code (including this callback) is executed when doing so.
```
I just want to check you are aware of this and that you are intentionally handling test environments 👆

File: app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+import io.kotlintest.specs.AbstractFreeSpec
+import io.kotlintest.specs.FreeSpec
+import kotlinx.coroutines.Dispatchers
+import kotlinx.coroutines.ExperimentalCoroutinesApi
+import kotlinx.coroutines.test.TestCoroutineDispatcher
+import kotlinx.coroutines.test.resetMain
+import kotlinx.coroutines.test.setMain
+
+@ExperimentalCoroutinesApi
+open class CoroutineFreeSpec(
```
Comment (heytherewill) [inline app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt:15]: `FreeCoroutineSpec` is a much better name. This sounds like a Spec without coroutines 😂

File: app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+    var dispatcher: TestCoroutineDispatcher = TestCoroutineDispatcher(),
+    body: AbstractFreeSpec.() -> Unit = {}
+) : FreeSpec(body) {
+    var dispatcherProvider: DispatcherProvider = DispatcherProvider(dispatcher, dispatcher, Dispatchers.Main)
```
Comment (heytherewill) [inline app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt:19]: Why is main still used instead of a test dispatcher? 🤔

File: app/src/main/java/com/toggl/TogglApplication.kt (hunk 2 above)
Comment (daividssilverio) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: Actually, I was not.
Do you have a suggestion for a better place to kill the job? Or maybe we shouldn't be doing this 🤔

File: app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt (hunk 4 above)
Comment (daividssilverio) [reply app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt:19]: The `Main` is replaced by the `TestCoroutineDispatcher` in the setup done in this class.

File: app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt (hunk 3 above)
Comment (daividssilverio) [reply app/src/test/java/com/toggl/common/CoroutineFreeSpec.kt:15]: Fair enough.

File: app/src/main/java/com/toggl/TogglApplication.kt (hunk 2 above)
Comment (semanticer) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: > no user code (including this callback) is executed when doing so.

This part is quite worrisome

However, we could maybe use [ProcessLifecycleOwner](https://developer.android.com/reference/androidx/lifecycle/ProcessLifecycleOwner) ?
Here is some guy implementing analytics with it for reference: https://proandroiddev.com/android-processlifecycleowner-by-example-2f965061b9da

Comment (daividssilverio) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: 🤔 Let's give it a try. Not exactly like the example though. That would make the store scope get cleared when going to background and that's not what we want.

Comment (daividssilverio) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: Yeah... I couldn't find a reliable way of detecting if the application has been killed/terminated by the OS.

Maybe we shouldn't do anything specific then 🤔 and that makes sense as well...
When the application is killed, everything is killed alongside with it anyway.

Removing the `SupervisorJob` completely doesn't change the behaviour we want to achieve.

Comment (daividssilverio) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: I don't want to add counters for non destroyed activities/services... that sounds like a bad idea.
What we could achieve.

Comment (semanticer) [reply app/src/main/java/com/toggl/TogglApplication.kt:55]: Oh please no counters 🙏
And yes you are probably right, we don't need to worry about this that much.
