### PR TITLE
🔨 Respect 24hours user prefs & fix Settings toggle dispatcher

### LINKED ISSUE #860: Dispatch the setting's toggle/switch actions
We just need to bind the actions.
(They are currently read-only)

### LINKED ISSUE #875: Consider 12/24 hour mode user preferences in the calendar
We are currently using a static 24 hours mode.

### PR DESCRIPTION
**Pull request by daividssilverio**
### Summary
This PR does two things:
- Makes the calendar hour indicators respect the 24 hour clock user preferences.
- Makes the settings toggle dispatch the tap action when it's being clicked

### Technical considerations
#860 was sort of working already, but you had to click on the row (not the switch) to trigger the toggle switch. So I've made a click on the toggle itself dispatch a tap action.
It looks like the switch implementation was broken before compose alpha-03, and the `onCheckedChange` was being invoked when it shouldn't. If you the code here without updating to compose alpha-03 (#880), the switches will enter into feedback loop.

### Why is it done like this and not some other way?
🤷‍♂️
I've fixed #860 because it became easier to test the calendar then.

### Relationships
Closes #875 
Closes #860 
Depends on #880 

### Pull Request checklist
- [x] The code does not hinder the app's performance
- [x] The code does not introduce regressions
- [x] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

### Pointers
Do a functional test, ideally after #880 is merged. Or update the compose

### Review template

- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
🦑 it.

### CODE REVIEW

File: calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt [hunk 1]
```diff
@@ -13,13 +13,23 @@ class CalendarBackgroundDrawingDelegate(
...
     private val verticalLineLeftMargin: Float,
     private val timeSliceStartX: Float,
-    private val hoursX: Float
+    private val hoursX: Float,
+    use24HoursFormat: Boolean,
 ) {
-    private val format = DateTimeFormatter.ofPattern("HH:mm")
+    private val format: DateTimeFormatter
+        get() = if (use24HoursFormat) DateTimeFormatter.ofPattern("HH:mm")
+        else DateTimeFormatter.ofPattern("h a")
```
Comment (heytherewill) [inline calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt:21]: Is this the only place where we wanna distinguish between 24 and 12 hour format? If so, that's fine. Otherwise, extract the pattern for consistency across the board ™️

**Review by heytherewill — APPROVED** [review]

File: calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt (hunk 1 above)
Comment (daividssilverio) [reply calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt:21]: This exact pattern is only used here. We also use the 24hours preferences in the edit view and the calendar contextual menu, but with different patterns. Putting these patterns in together in some file wouldn't hurt I guess. We used to have a `TimeFormat` in the old implementation, we could have a constants file to keep things organized and help making changes when needed.

Comment (heytherewill) [reply calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt:21]: If we both see value in that, let's implement it :)

Comment (daividssilverio) [reply calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarBackgroundDrawingDelegate.kt]: 🤔 what do you think of the `TimeFormats` helper?

File: calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarItemDrawingDelegate.kt [hunk 2]
```diff
@@ -84,7 +83,7 @@ class CalendarItemDrawingDelegate(
         color = editingHoursLabelsTextColor
         textSize = editingHoursLabelsTextSize
     }
-    private val hourFormat = DateTimeFormatter.ofPattern("HH:mm")
```
Comment (heytherewill) [inline calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarItemDrawingDelegate.kt:87]: Wait, why is this hardcoded to twenty four hours?

File: common-android/src/main/java/com/toggl/common/extensions/OffsetDateTimeExtensions.kt [hunk 3]
```diff
@@ -10,7 +11,7 @@ import java.time.temporal.ChronoUnit
 import java.time.temporal.TemporalUnit
 import kotlin.math.absoluteValue
 
-private val timeFormatter = DateTimeFormatter.ofPattern("HH:mm")
+private val timeFormatter = TimeFormats.TwentyFourHoursFormat.hoursAndMinutes
```
Comment (heytherewill) [inline common-android/src/main/java/com/toggl/common/extensions/OffsetDateTimeExtensions.kt:14]: Same here: Why is it constrained to `TwentyFourHoursFormat` instead of respecting the user's settings?

File: calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarItemDrawingDelegate.kt (hunk 2 above)
Comment (daividssilverio) [reply calendar/src/main/java/com/toggl/calendar/calendarday/ui/views/CalendarItemDrawingDelegate.kt:87]: Leftovers from when we didn't have the user preferences available. Fixing it.

File: common-android/src/main/java/com/toggl/common/extensions/OffsetDateTimeExtensions.kt (hunk 3 above)
Comment (daividssilverio) [reply common-android/src/main/java/com/toggl/common/extensions/OffsetDateTimeExtensions.kt:14]: Same reason I suppose. Fixing it as well!
