### PR TITLE
Fix StartEditReducer done button logic

### LINKED ISSUE #399: Fix time entry updates
## Description
Currently our StartEditReducer doesn't handle time entry updates properly.
We are currently updating only the `description` and `billable` fields of the time entries during edition. 

## Definition of done
- [x] The `StartEditReducer` can start manual time entries, currently the `TimeEntryReducer` is able to handle that, but we only forward actions from the `StartEditReducer` to start time entries or edit existing ones
- [x] The `StartEditReducer` maps correctly all the fields from the `EditableTimeEntry` to a `TimeEntry` when handling `DoneButtonTapped`. Currently it only updates the `description` and the `billable` flag.
- [ ] Tests were added to verify the behaviour described above
- [ ] The documentation is updated to reflect the changes done in this PR

### PR DESCRIPTION
**Pull request by heytherewill**
### Summary
This is a nice catch found by Des. Our creation logic was all wrong

### Relationships
Closes #399 

### Pull Request checklist
- [X] The code does not hinder the app's performance
- [X] The code does not introduce regressions
- [X] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

### Pointers
Review commit by commit

### Review template
- [ ] The code is thoroughly tested in well written and resilient manner
- [ ] The code is performant and leads to an optimal user experience
- [ ] The code is testable and does not cut corners for the sake of delivering
- [ ] The code considers older platforms well and will work in older devices just like it will in new ones

## Merge permissions
Only myself

### CODE REVIEW

File: common-feature/src/main/java/com/toggl/common/feature/timeentry/extensions/EditableTimeEntryExtensions.kt [hunk 1]
```diff
@@ -9,6 +9,8 @@ fun EditableTimeEntry.isNew() = this.startTime == null
 fun EditableTimeEntry.isRunning() = this.duration == null
 fun EditableTimeEntry.isRunningOrNew() = isRunning() || isNew()
 fun EditableTimeEntry.isStopped() = this.startTime != null && this.duration != null
+fun EditableTimeEntry.isRepresentingGroup() = this.ids.size > 1
+fun EditableTimeEntry.needsPersisting() = this.ids.isEmpty()
```
Comment (daividssilverio) [inline common-feature/src/main/java/com/toggl/common/feature/timeentry/extensions/EditableTimeEntryExtensions.kt:13]: `needsToBeCreated`, `wasNotPersisted`,  or something that gives the idea of "creation" could make more sense.
I say that because time entries that are being updated also need to be persisted. It read weird to me.

Comment (heytherewill) [reply common-feature/src/main/java/com/toggl/common/feature/timeentry/extensions/EditableTimeEntryExtensions.kt:13]: Fair point
